# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1521ab21b8f38e8565c1581d82c4b9443e4fbcbdc060490dafe7bbd35a1e2fd1159dcf5d14dd49af63e5ade76acdcbb455e4dec231894ac649e64e25c02b4232

test:
  secret_key_base: 8bfcec7d0c53228857b4fed49e9e1be57634b041c9d2687b8d593a83a1cf43f9bcb30fe8206e3c580b46c2bacd9ec7b37c3bcfe11760d2bbddcd2a029adf5624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
